/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PpAmbulanceWlList {
    }
}
declare global {
    interface HTMLPpAmbulanceWlListElement extends Components.PpAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPpAmbulanceWlListElement: {
        prototype: HTMLPpAmbulanceWlListElement;
        new (): HTMLPpAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pp-ambulance-wl-list": HTMLPpAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PpAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pp-ambulance-wl-list": PpAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pp-ambulance-wl-list": LocalJSX.PpAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPpAmbulanceWlListElement>;
        }
    }
}
